name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/atividade:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 201.23.3.86 >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "echo 'SSH connection successful!'"

    - name: Stop any process using port 8102
      run: |
        ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "
          sudo fuser -k 8102/tcp || echo 'No process found on port 8102';
          docker stop \$(docker ps -aq) || echo 'No containers to stop';
          docker rm \$(docker ps -aq) || echo 'No containers to remove';
        "

    - name: Deploy container to remote server
      run: |
        ssh -i ~/.ssh/id_rsa aluno@201.23.3.86 "
          docker info || sudo systemctl start docker;
          docker pull ${{ secrets.DOCKER_USERNAME }}/atividade:latest &&
          docker run -d -p 8102:8080 --name atividade ${{ secrets.DOCKER_USERNAME }}/atividade:latest;
          docker ps | grep atividade || echo 'Container failed to start';
        "
